/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import BLL.ExecuteData;
import BLL.GetData;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
/**
 *
 * @author Xuan Quynh Phuong
 */
public class Audit extends javax.swing.JFrame {

    /**
     * Creates new form Audit
     */
    public Audit() {
        initComponents();
        LoadComboBoxObjectName();
        LoadComboBoxObjectSchema();
    }
    private GetData x = new GetData();
    private ExecuteData y = new ExecuteData();
    ArrayList tableName = x.getTableName();
    ArrayList objectSchema=x.getObjectSchema();
    String statement;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPolicyName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCreateAuditPolicy = new javax.swing.JButton();
        ckbInsert = new javax.swing.JCheckBox();
        ckbDelete = new javax.swing.JCheckBox();
        ckbUpdate = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        cboObjectName = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cboObjectSchema = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Thiết lập Audit Policy");

        jLabel2.setText("Nhập tên Audit:");

        jLabel3.setText("Kiểm toán các thao tác:");

        btnCreateAuditPolicy.setText("Thiết lập");
        btnCreateAuditPolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAuditPolicyActionPerformed(evt);
            }
        });

        ckbInsert.setText("INSERT");

        ckbDelete.setText("DELETE");

        ckbUpdate.setText("UPDATE");

        jLabel4.setText("Chọn bảng cần Audit:");

        cboObjectName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboObjectNameItemStateChanged(evt);
            }
        });

        jLabel5.setText("Chọn tên user:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckbInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckbDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckbUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68))))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(btnCreateAuditPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboObjectName, javax.swing.GroupLayout.Alignment.TRAILING, 0, 203, Short.MAX_VALUE)
                    .addComponent(txtPolicyName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cboObjectSchema, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(cboObjectSchema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboObjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbInsert)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbDelete)
                .addGap(50, 50, 50)
                .addComponent(btnCreateAuditPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateAuditPolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAuditPolicyActionPerformed
        // TODO add your handling code here:
        try
        {
            String objectName=cboObjectName.getSelectedItem().toString();
            
            if(txtPolicyName.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Vui long nhap ten!","Canh bao",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                if(ckbInsert.isSelected()){
                    statement="insert";
                }
                if(ckbUpdate.isSelected()){
                    statement="update";
                }
                if(ckbDelete.isSelected()){
                    statement="delete";
                }
                if(ckbInsert.isSelected()&&ckbUpdate.isSelected())
                {
                    statement="insert, update";
                }
                if(ckbInsert.isSelected()&&ckbDelete.isSelected())
                {
                    statement="insert, delete";
                }
                if(ckbUpdate.isSelected()&&ckbDelete.isSelected())
                {
                    statement="update, delete";
                }
                if(ckbInsert.isSelected()&&ckbDelete.isSelected()&&ckbInsert.isSelected())
                {
                    statement="insert, update, delete";
                }
                String a=cboObjectName.getSelectedItem().toString();
                String b=txtPolicyName.getText();
                String c=statement;
                String d=cboObjectSchema.getSelectedItem().toString();
                y.CreateAuditPolicy(d,a,b,c);
                JOptionPane.showMessageDialog(this, "Thiet lap audit policy thanh cong!","Thông Báo",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch (Exception e)
        {
            e.getMessage();
        }
    }//GEN-LAST:event_btnCreateAuditPolicyActionPerformed

    private void LoadComboBoxObjectName()
    {
        for(var e:tableName)
        {
            cboObjectName.addItem(e.toString());
        }
    }
    
    private void LoadComboBoxObjectSchema()
    {
        for(var e:objectSchema)
        {
            cboObjectSchema.addItem(e.toString());
        }
    }
    
    private void cboObjectNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboObjectNameItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboObjectNameItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Audit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Audit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Audit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Audit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Audit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAuditPolicy;
    private javax.swing.JComboBox<String> cboObjectName;
    private javax.swing.JComboBox<String> cboObjectSchema;
    private javax.swing.JCheckBox ckbDelete;
    private javax.swing.JCheckBox ckbInsert;
    private javax.swing.JCheckBox ckbUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtPolicyName;
    // End of variables declaration//GEN-END:variables
}
