/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BLL.ExecuteData;
import BLL.GetData;
import BLL.UpdateData;
import Ultilities.ConvertData.ConvertDataORCL;
import Ultilities.swing.ButtonColumn;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ScrollPaneConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phatl
 */
public class SystemForm extends javax.swing.JPanel {

    /**
     * Creates new form SystemForm
     */
    private boolean flag = true;
    private GetData x = new GetData();
    private ExecuteData y = new ExecuteData();
    private UpdateData up = new UpdateData();
    ArrayList tableName = x.getTableName();
    String statement;
    
    @SuppressWarnings("unchecked")
    public SystemForm() {
        initComponents();

        comboBoxSuggestion.addItem("SGA");
        comboBoxSuggestion.addItem("PGA");
        comboBoxSuggestion.addItem("Process");
        comboBoxSuggestion.addItem("ControlFile");
        comboBoxSuggestion.addItem("Instance");
        comboBoxSuggestion.addItem("SessionProcess");
        comboBoxSuggestion.addItem("SPFile");
        comboBoxSuggestion.addItem("DataFile");
        comboBoxSuggestion.addItem("Database");
        comboBoxSuggestion.addItem("Policy Is Valid");
                       
        showDataOnTable(table1,x.showSGA());
        LoadComboBoxObjectName();
        showDataOnTable(table2,x.getDataRole ());
        flag = false;
        lbl_Pass.setVisible (flag);
        txt_Pass.setVisible (flag);
        cbo_objectname.setSelectedIndex (0);
        
    }

    public void showDataOnTable(Ultilities.swing.Table table,ArrayList arr)
    {
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        String[] columnNames = (String[])arr.get(0);
        String[][] data = ConvertDataORCL.ConvertObject2DToString2D((Object[][])arr.get(1));
        model.setDataVector(data, columnNames);
        countRecord.setText("Số dòng: "+data.length);
    }
    public void showDataOnTable_1(Ultilities.swing.Table table , ArrayList arr)
    {
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        String[] columnNames = (String[])arr.get(0);
        String[][] data = ConvertDataORCL.ConvertObject2DToString2D((Object[][])arr.get(1));
        model.setDataVector(data, columnNames);
        model.addColumn("");
        ButtonColumn btnCol = new ButtonColumn(table, kill, columnNames.length,"Kill");
        countRecord.setText("Số dòng: "+data.length);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        TTHT = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboBoxSuggestion = new Ultilities.swing.ComboBoxSuggestion();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new Ultilities.swing.Table();
        countRecord = new javax.swing.JLabel();
        buttonGradient1 = new Ultilities.swing.ButtonGradient();
        SESSION = new javax.swing.JPanel();
        btnRefresh = new Ultilities.swing.ButtonGradient();
        btnDemo = new Ultilities.swing.ButtonGradient();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_tab2 = new Ultilities.swing.Table();
        numRecord_tab2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        AUDIT = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPolicyName = new javax.swing.JTextField();
        cboObjectName = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ckbInsert = new javax.swing.JCheckBox();
        ckbUpdate = new javax.swing.JCheckBox();
        ckbDelete = new javax.swing.JCheckBox();
        btnCreateAuditPolicy = new javax.swing.JButton();
        btn_showaudit = new javax.swing.JButton();
        btn_XemTT = new javax.swing.JButton();
        QL_ROLE = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table2 = new Ultilities.swing.Table();
        Panel2 = new javax.swing.JPanel();
        cbo_objectname = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        ckb_insert = new javax.swing.JCheckBox();
        ckb_delete = new javax.swing.JCheckBox();
        cbk_update = new javax.swing.JCheckBox();
        ckb_select = new javax.swing.JCheckBox();
        btn_InsertPriv = new javax.swing.JButton();
        btn_Revoke = new javax.swing.JButton();
        ckb_all = new javax.swing.JCheckBox();
        Control_ROLE = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lbl_Pass = new javax.swing.JLabel();
        txt_Pass = new javax.swing.JTextField();
        rdo_Pass = new javax.swing.JRadioButton();
        rdo_NotPass = new javax.swing.JRadioButton();
        txt_role_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_Create = new javax.swing.JButton();
        btn_updaterole = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Profile = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        buttonGradient3 = new Ultilities.swing.ButtonGradient();
        btn_CapNhat = new Ultilities.swing.ButtonGradient();
        btn_XoaProfile = new Ultilities.swing.ButtonGradient();
        cb_ListProfile = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        lb_slProfile = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_Profile = new Ultilities.swing.Table();
        lb_slProfile1 = new javax.swing.JLabel();

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTabbedPane1.setVerifyInputWhenFocusTarget(false);
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        TTHT.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Hiển Thị Thông Tin");

        comboBoxSuggestion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboBoxSuggestion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxSuggestionItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(272, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxSuggestion, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxSuggestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(table1);

        countRecord.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        countRecord.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        countRecord.setText("jLabel2");
        countRecord.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        buttonGradient1.setText("Quản Lý Tablespace");
        buttonGradient1.setColor2(new java.awt.Color(0, 255, 153));
        buttonGradient1.setSizeSpeed(5.0F);
        buttonGradient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TTHTLayout = new javax.swing.GroupLayout(TTHT);
        TTHT.setLayout(TTHTLayout);
        TTHTLayout.setHorizontalGroup(
            TTHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TTHTLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(TTHTLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(buttonGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(366, 366, 366)
                .addComponent(countRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        TTHTLayout.setVerticalGroup(
            TTHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TTHTLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(TTHTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Thông tin hệ thống", TTHT);

        SESSION.setBackground(new java.awt.Color(255, 255, 255));
        SESSION.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                SESSIONComponentShown(evt);
            }
        });

        btnRefresh.setText("Làm Mới");
        btnRefresh.setBorderPainted(false);
        btnRefresh.setColor2(new java.awt.Color(51, 51, 255));
        btnRefresh.setFocusPainted(false);
        btnRefresh.setFocusable(false);
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefresh.setSizeSpeed(5.0F);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnDemo.setText("Demo");
        btnDemo.setColor1(new java.awt.Color(153, 0, 255));
        btnDemo.setColor2(new java.awt.Color(255, 0, 255));
        btnDemo.setFocusPainted(false);
        btnDemo.setFocusable(false);
        btnDemo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDemo.setSizeSpeed(5.0F);
        btnDemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDemoActionPerformed(evt);
            }
        });

        table_tab2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_tab2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(table_tab2);

        numRecord_tab2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numRecord_tab2.setText("jLabel2");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("QUẢN LÝ SESSION");

        javax.swing.GroupLayout SESSIONLayout = new javax.swing.GroupLayout(SESSION);
        SESSION.setLayout(SESSIONLayout);
        SESSIONLayout.setHorizontalGroup(
            SESSIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(SESSIONLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numRecord_tab2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 338, Short.MAX_VALUE)
                .addComponent(btnDemo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SESSIONLayout.setVerticalGroup(
            SESSIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SESSIONLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(SESSIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDemo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numRecord_tab2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Quản lý session", SESSION);

        AUDIT.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Thiết lập Audit Policy");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nhập tên Audit:");

        txtPolicyName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cboObjectName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboObjectName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboObjectNameItemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Chọn bảng cần Audit:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Kiểm toán các thao tác:");

        ckbInsert.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckbInsert.setText("INSERT");

        ckbUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckbUpdate.setText("UPDATE");

        ckbDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckbDelete.setText("DELETE");

        btnCreateAuditPolicy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCreateAuditPolicy.setText("Thiết lập");
        btnCreateAuditPolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAuditPolicyActionPerformed(evt);
            }
        });

        btn_showaudit.setText("Audit");
        btn_showaudit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_showauditMouseClicked(evt);
            }
        });

        btn_XemTT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_XemTT.setText("Xem thông tin");
        btn_XemTT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_XemTTMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AUDITLayout = new javax.swing.GroupLayout(AUDIT);
        AUDIT.setLayout(AUDITLayout);
        AUDITLayout.setHorizontalGroup(
            AUDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AUDITLayout.createSequentialGroup()
                .addGroup(AUDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AUDITLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138)
                        .addGroup(AUDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckbInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckbDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckbUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AUDITLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_XemTT))
                    .addGroup(AUDITLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(AUDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(43, 43, 43)
                        .addGroup(AUDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboObjectName, 0, 210, Short.MAX_VALUE)
                            .addComponent(txtPolicyName)))
                    .addGroup(AUDITLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(btnCreateAuditPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btn_showaudit, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        AUDITLayout.setVerticalGroup(
            AUDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AUDITLayout.createSequentialGroup()
                .addGroup(AUDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AUDITLayout.createSequentialGroup()
                        .addGroup(AUDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AUDITLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel2))
                            .addGroup(AUDITLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(btn_XemTT)))
                        .addGap(30, 30, 30)
                        .addGroup(AUDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(AUDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cboObjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ckbInsert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AUDITLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(1, 1, 1)))
                .addComponent(ckbUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbDelete)
                .addGap(32, 32, 32)
                .addGroup(AUDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_showaudit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateAuditPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(220, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quản Lý Audit", AUDIT);

        QL_ROLE.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin role", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane3.setViewportView(table2);

        Panel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thiệt lập quyền cho role", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        Panel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cbo_objectname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbo_objectname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_objectnameActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Đối tượng");

        ckb_insert.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckb_insert.setText("INSERT");

        ckb_delete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckb_delete.setText("DELETE");

        cbk_update.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbk_update.setText("UPDATE");

        ckb_select.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckb_select.setText("SELECT");

        btn_InsertPriv.setText("Cấp quyền");
        btn_InsertPriv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_InsertPrivMousePressed(evt);
            }
        });

        btn_Revoke.setText("Thu hồi");
        btn_Revoke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_RevokeMousePressed(evt);
            }
        });

        ckb_all.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckb_all.setText("TẤT CẢ");

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addComponent(ckb_insert)
                        .addGap(18, 18, 18)
                        .addComponent(ckb_delete)
                        .addGap(18, 18, 18)
                        .addComponent(cbk_update)
                        .addGap(18, 18, 18)
                        .addComponent(ckb_select)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ckb_all))
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbo_objectname, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btn_InsertPriv, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_Revoke, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbo_objectname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckb_insert)
                    .addComponent(ckb_delete)
                    .addComponent(cbk_update)
                    .addComponent(ckb_select)
                    .addComponent(ckb_all))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_InsertPriv, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Revoke, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout QL_ROLELayout = new javax.swing.GroupLayout(QL_ROLE);
        QL_ROLE.setLayout(QL_ROLELayout);
        QL_ROLELayout.setHorizontalGroup(
            QL_ROLELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QL_ROLELayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QL_ROLELayout.setVerticalGroup(
            QL_ROLELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QL_ROLELayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jTabbedPane1.addTab("Quản lý role", QL_ROLE);

        Control_ROLE.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thiệt lập role", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lbl_Pass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Pass.setText("Mật khẩu");

        buttonGroup1.add(rdo_Pass);
        rdo_Pass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdo_Pass.setText("Mật khẩu");
        rdo_Pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_PassActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdo_NotPass);
        rdo_NotPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdo_NotPass.setText("Không mật khẩu");
        rdo_NotPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_NotPassActionPerformed(evt);
            }
        });

        txt_role_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tên role");

        btn_Create.setText("Tạo");
        btn_Create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CreateMouseClicked(evt);
            }
        });

        btn_updaterole.setText("Cập nhật");
        btn_updaterole.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_updateroleMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_Pass)
                    .addComponent(jLabel5))
                .addGap(41, 41, 41)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_role_name, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdo_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdo_NotPass))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btn_Create, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_updaterole, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_role_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdo_Pass))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Pass)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(rdo_NotPass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Create, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_updaterole, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("THIẾT LẬP ROLES");

        javax.swing.GroupLayout Control_ROLELayout = new javax.swing.GroupLayout(Control_ROLE);
        Control_ROLE.setLayout(Control_ROLELayout);
        Control_ROLELayout.setHorizontalGroup(
            Control_ROLELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Control_ROLELayout.createSequentialGroup()
                .addContainerGap(210, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(263, 263, 263))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Control_ROLELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Control_ROLELayout.setVerticalGroup(
            Control_ROLELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Control_ROLELayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(302, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Role", Control_ROLE);

        Profile.setBackground(new java.awt.Color(255, 255, 255));
        Profile.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ProfileComponentShown(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jPanel11.setLayout(new java.awt.GridLayout(1, 3, 5, 0));

        buttonGradient3.setForeground(new java.awt.Color(0, 0, 0));
        buttonGradient3.setText("Tạo mới");
        buttonGradient3.setColor1(new java.awt.Color(51, 255, 204));
        buttonGradient3.setColor2(new java.awt.Color(0, 204, 204));
        buttonGradient3.setFocusPainted(false);
        buttonGradient3.setFocusable(false);
        buttonGradient3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonGradient3.setSizeSpeed(5.0F);
        buttonGradient3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient3ActionPerformed(evt);
            }
        });
        jPanel11.add(buttonGradient3);

        btn_CapNhat.setForeground(new java.awt.Color(0, 0, 0));
        btn_CapNhat.setText("Cập nhật");
        btn_CapNhat.setColor1(new java.awt.Color(255, 255, 0));
        btn_CapNhat.setColor2(new java.awt.Color(255, 255, 153));
        btn_CapNhat.setFocusPainted(false);
        btn_CapNhat.setFocusable(false);
        btn_CapNhat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_CapNhat.setSizeSpeed(5.0F);
        btn_CapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhatActionPerformed(evt);
            }
        });
        jPanel11.add(btn_CapNhat);

        btn_XoaProfile.setText("Xóa");
        btn_XoaProfile.setColor1(new java.awt.Color(255, 0, 102));
        btn_XoaProfile.setColor2(new java.awt.Color(255, 102, 102));
        btn_XoaProfile.setFocusPainted(false);
        btn_XoaProfile.setFocusable(false);
        btn_XoaProfile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_XoaProfile.setSizeSpeed(5.0F);
        btn_XoaProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaProfileActionPerformed(evt);
            }
        });
        jPanel11.add(btn_XoaProfile);

        cb_ListProfile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cb_ListProfile.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_ListProfileItemStateChanged(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Thông Tin Profile");

        lb_slProfile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_slProfile.setText("Số Lượng Profile:");

        table_Profile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(table_Profile);

        lb_slProfile1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lb_slProfile1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_slProfile1.setText("Quản Lý Profile");
        lb_slProfile1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_ListProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_slProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(lb_slProfile1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_slProfile1)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_ListProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_slProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout ProfileLayout = new javax.swing.GroupLayout(Profile);
        Profile.setLayout(ProfileLayout);
        ProfileLayout.setHorizontalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ProfileLayout.setVerticalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileLayout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("Profile", Profile);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_updateroleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateroleMousePressed
        // TODO add your handling code here:
        String name = txt_role_name.getText ();
        String pass = txt_Pass.getText ();
        if(rdo_Pass.isSelected ())
        {
            up.alterRoleWithPass (name,pass);
        }
        else
        up.alterRoleWithNotPass (name);
        JOptionPane.showMessageDialog(this, "Cập nhật role thành công!","Thông Báo",JOptionPane.INFORMATION_MESSAGE);
        showDataOnTable(table2,x.getDataRole ());
    }//GEN-LAST:event_btn_updateroleMousePressed

    private void btn_CreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CreateMouseClicked
        // TODO add your handling code here:
        String name = txt_role_name.getText ();
        String pass = txt_Pass.getText ();
        if(rdo_Pass.isSelected ())
        {
            up.createRoleWithPass (name,pass);
        }
        else
        up.createRoleWithNotPass (name);
        JOptionPane.showMessageDialog(this, "Tạo role thành công!","Thông Báo",JOptionPane.INFORMATION_MESSAGE);
        table2.updateUI ();
    }//GEN-LAST:event_btn_CreateMouseClicked

    private void rdo_NotPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_NotPassActionPerformed
        // TODO add your handling code here:
        if(rdo_NotPass.isSelected ())
        {
            flag = false;
            lbl_Pass.setVisible (flag);
            txt_Pass.setVisible (flag);
        }
        else
        {
            flag = true;
            lbl_Pass.setVisible (flag);
            txt_Pass.setVisible (flag);
        }
    }//GEN-LAST:event_rdo_NotPassActionPerformed

    private void rdo_PassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_PassActionPerformed
        // TODO add your handling code here:
        if(rdo_Pass.isSelected ())
        {
            flag = true;
            lbl_Pass.setVisible (flag);
            txt_Pass.setVisible (flag);
        }
        else
        {
            flag = false;
            lbl_Pass.setVisible (flag);
            txt_Pass.setVisible (flag);
        }
    }//GEN-LAST:event_rdo_PassActionPerformed

    private void btn_RevokeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RevokeMousePressed
        // TODO add your handling code here:
        String priv = "";
        int row = table2.getSelectedRow ();
        String name = table2.getValueAt (row,0).toString ();
        String obj = cbo_objectname.getSelectedItem ().toString ();
        if(ckb_all.isSelected ())
        {
            up.revokeAllToRole (name,obj);

        }
        else
        {
            for(Component com : Panel2.getComponents ())
            {
                if(com instanceof JCheckBox)
                {
                    JCheckBox box = (JCheckBox)com;
                    if(box.isSelected ())
                    {
                        priv += box.getText () + ",";
                    }
                }
            }
            try {
                up.revokeRole (priv.substring (0,priv.length ()-1),name,obj);
                JOptionPane.showMessageDialog(this, String.format ("Thu hồi quyền cho %s thành công!", name),"Thông Báo",JOptionPane.INFORMATION_MESSAGE);
                loadpriv ();
            } catch ( Exception e ) {
            }
        }

    }//GEN-LAST:event_btn_RevokeMousePressed

    private void btn_InsertPrivMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_InsertPrivMousePressed
        // TODO add your handling code here:
        String priv = "";
        int row = table2.getSelectedRow ();
        String name = table2.getValueAt (row,0).toString ();
        String obj = cbo_objectname.getSelectedItem ().toString ();
        if(ckb_all.isSelected ())
        {
            up.grantAllToRole (name,obj);

        }
        else
        {
            for(Component com : Panel2.getComponents ())
            {
                if(com instanceof JCheckBox)
                {
                    JCheckBox box = (JCheckBox)com;
                    if(box.isSelected ())
                    {
                        priv += box.getText ()+ ",";
                    }
                }
            }
            try
            {
                up.grantPrivToRole (priv.substring (0,priv.length ()-1),name,obj);
                JOptionPane.showMessageDialog(this, String.format ("Cấp quyền cho %s thành công!", name),"Thông Báo",JOptionPane.INFORMATION_MESSAGE);
                loadpriv ();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, String.format ("Quyền %s có thể đã được cấp! Vui lòng kiểm tra lại!", name),"Thông Báo",JOptionPane.INFORMATION_MESSAGE);
            }

        }

    }//GEN-LAST:event_btn_InsertPrivMousePressed

    private void cbo_objectnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_objectnameActionPerformed
        // TODO add your handling code here:
        loadpriv ();
    }//GEN-LAST:event_cbo_objectnameActionPerformed

    private void btn_XemTTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_XemTTMouseClicked
        // TODO add your handling code here:
        ShowAudit sau = new ShowAudit ();
        sau.setVisible (true);
    }//GEN-LAST:event_btn_XemTTMouseClicked

    private void btn_showauditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_showauditMouseClicked
        // TODO add your handling code here:
        ShowAuditPolicy saup = new ShowAuditPolicy ();
        saup.setVisible (true);
    }//GEN-LAST:event_btn_showauditMouseClicked

    private void btnCreateAuditPolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAuditPolicyActionPerformed
        // TODO add your handling code here:
        try
        {
            String objectName=cboObjectName.getSelectedItem().toString();

            if(txtPolicyName.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Vui long nhap ten!","Canh bao",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                if(ckbInsert.isSelected()){
                    statement="insert";
                }
                if(ckbUpdate.isSelected()){
                    statement="update";
                }
                if(ckbDelete.isSelected()){
                    statement="delete";
                }
                if(ckbInsert.isSelected()&&ckbUpdate.isSelected())
                {
                    statement="insert, update";
                }
                if(ckbInsert.isSelected()&&ckbDelete.isSelected())
                {
                    statement="insert, delete";
                }
                if(ckbUpdate.isSelected()&&ckbDelete.isSelected())
                {
                    statement="update, delete";
                }
                if(ckbInsert.isSelected()&&ckbDelete.isSelected()&&ckbInsert.isSelected())
                {
                    statement="insert, update, delete";
                }
                String a=cboObjectName.getSelectedItem().toString();
                String b=txtPolicyName.getText();
                String c=statement;
                /*Chỗ chỉnh sửa*/
                String d="nguoidung1";

                y.CreateAuditPolicy(d,a,b,c);
                JOptionPane.showMessageDialog(this, "Thiết lập policy thành công!","Thông Báo",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Thiet lap audit policy thất bại !","Thông Báo",JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnCreateAuditPolicyActionPerformed

    // tab 3
    private void cboObjectNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboObjectNameItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboObjectNameItemStateChanged

    private void btnDemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDemoActionPerformed
        Demo_KillSession t = new Demo_KillSession();
        t.setVisible(true);
    }//GEN-LAST:event_btnDemoActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        showDataOnTable(table_tab2, x.showSessionCurrent());
        numRecord_tab2.setText("Số lượng Session: "+table_tab2.getRowCount());
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void buttonGradient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient1ActionPerformed
        S_Tablespaces t = new S_Tablespaces();
        t.setVisible(true);
    }//GEN-LAST:event_buttonGradient1ActionPerformed

    private void comboBoxSuggestionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxSuggestionItemStateChanged
        String value = evt.getItem().toString();
        switch(value){
            case "SGA":
            showDataOnTable(table1,x.showSGA());
            break;
            case "PGA":
            showDataOnTable(table1,x.showPGA());
            break;
            case "ControlFile":
            showDataOnTable(table1,x.showControlFile());
            break;
            case "SPFile":
            showDataOnTable(table1,x.showSPFile());
            break;
            case "Instance":
            showDataOnTable(table1,x.showInfoInstance());
            break;
            case "DataFile":
            showDataOnTable(table1,x.showDataFile());
            break;
            case "Process":
            showDataOnTable(table1,x.showProcess());
            break;
            case "SessionProcess":
            showDataOnTable(table1,x.showProcessOfSession());
            break;
            case "Policy Is Valid":
            showDataOnTable(table1,x.getAllPoliciesInDB());
            break;
            case "Database":
            showDataOnTable(table1,x.showInfoDatabase());
            break;
        }
    }//GEN-LAST:event_comboBoxSuggestionItemStateChanged

    //tab profile
    
    public void loadDataProfile(){
        //load combobox list name profile
        cb_ListProfile.removeAllItems();
        Object[][] nameProfiles = x.getAllProfileName();
        int n = nameProfiles.length;
        for(int i =0;i<n;i++)
        {
            cb_ListProfile.addItem(nameProfiles[i][0].toString());
        }
        lb_slProfile.setText("Số Lượng Profile: "+n);
    }
    
    private void cb_ListProfileItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_ListProfileItemStateChanged
        ArrayList temp = x.getDetailsProfile(evt.getItem().toString());
        DefaultTableModel model = (DefaultTableModel)table_Profile.getModel();
        model.setDataVector((Object[][])temp.get(1), (Object[])temp.get(0));
    }//GEN-LAST:event_cb_ListProfileItemStateChanged

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void btn_XoaProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaProfileActionPerformed
        String nameProfile = cb_ListProfile.getSelectedItem().toString();
        if(JOptionPane.showConfirmDialog(this, "Bạn chắc chắn xóa Profile: "+nameProfile) == JOptionPane.YES_OPTION)
            if(ExecuteData.DeleteProfile(nameProfile)){
                JOptionPane.showMessageDialog(this, "Xóa Profile '"+ nameProfile +"' thành công !");
                loadDataProfile();
            }
            else
                JOptionPane.showMessageDialog(this, "Xóa Profile '"+ nameProfile +"' thất bại !");
    }//GEN-LAST:event_btn_XoaProfileActionPerformed

    CreateProfile fCrePro = null;
    private void buttonGradient3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient3ActionPerformed
        if(fCrePro == null)
            fCrePro = new CreateProfile();
        fCrePro.setVisible(true);
        fCrePro.root = this;
    }//GEN-LAST:event_buttonGradient3ActionPerformed

    private void btn_CapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhatActionPerformed
        UpdateProfile f = new UpdateProfile();
        f.nameProfile = cb_ListProfile.getSelectedItem().toString();
        f.root = this;
        f.setVisible(true);
    }//GEN-LAST:event_btn_CapNhatActionPerformed

    private void SESSIONComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_SESSIONComponentShown
        showDataOnTable(table_tab2, x.showSessionCurrent());
        numRecord_tab2.setText("Số lượng Session: "+table_tab2.getRowCount());
    }//GEN-LAST:event_SESSIONComponentShown

    private void ProfileComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ProfileComponentShown
        loadDataProfile();
    }//GEN-LAST:event_ProfileComponentShown

    //tab 2 - manager session
    
    Action kill = new AbstractAction()
    {
        public void actionPerformed(ActionEvent e)
        {
            //remove row
            JTable table = (JTable)e.getSource();
            int indexRow = Integer.valueOf( e.getActionCommand() );
            
            String SID = table.getValueAt(indexRow, 0).toString();
            String SerialID = table.getValueAt(indexRow, 1).toString();
            if(ExecuteData.ExecuteSql(SID, SerialID))
            {
                JOptionPane.showMessageDialog(table, "Kill session thành công !","Thông Báo",JOptionPane.INFORMATION_MESSAGE);
                ((DefaultTableModel)table.getModel()).removeRow(indexRow);
            }
            else
            {
                JOptionPane.showMessageDialog(table, "Kill session thất bại !","Thông Báo",JOptionPane.ERROR_MESSAGE);
            }
        }
    };
    
    private void loadpriv()
    {
        try
        {
             for(Component com : Panel2.getComponents ())
             {
                    if(com instanceof JCheckBox)
                    {
                        JCheckBox box = (JCheckBox)com;
                           box.setSelected (false);

                    }
            }
            int row = table2.getSelectedRow ();
            String tablename =cbo_objectname.getSelectedItem ().toString ();
            String role = table2.getValueAt (row,0).toString ();
            ArrayList arr = x.getPrivRole (role,tablename);
            if(arr.size () ==0)
            {
                 for(Component com : Panel2.getComponents ())
                {
                    if(com instanceof JCheckBox)
                    {
                        JCheckBox box = (JCheckBox)com; 
                        box.setSelected (false);
                    }
                }
            }
            else
            {
                for(int i = 0; i<arr.size ();i++)
               {
                   String priv = arr.get (i).toString ();
                    for(Component com : Panel2.getComponents ())
                   {
                       if(com instanceof JCheckBox)
                       {
                           JCheckBox box = (JCheckBox)com;

                           String ckbselect = box.getText ();
                           if(priv.compareTo (ckbselect) ==0)
                           {
                               box.setSelected (true);
                               break;
                           }
                       }
                   }

               }
            }
            
        
        }
        catch(Exception ex)
        {
                
        }
    }    
    private void LoadComboBoxObjectName()
    {
        for(var e:tableName)
        {
            cboObjectName.addItem(e.toString());
            cbo_objectname.addItem (e.toString ());
        }
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AUDIT;
    private javax.swing.JPanel Control_ROLE;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Profile;
    private javax.swing.JPanel QL_ROLE;
    private javax.swing.JPanel SESSION;
    private javax.swing.JPanel TTHT;
    private javax.swing.JButton btnCreateAuditPolicy;
    private Ultilities.swing.ButtonGradient btnDemo;
    private Ultilities.swing.ButtonGradient btnRefresh;
    private Ultilities.swing.ButtonGradient btn_CapNhat;
    private javax.swing.JButton btn_Create;
    private javax.swing.JButton btn_InsertPriv;
    private javax.swing.JButton btn_Revoke;
    private javax.swing.JButton btn_XemTT;
    private Ultilities.swing.ButtonGradient btn_XoaProfile;
    private javax.swing.JButton btn_showaudit;
    private javax.swing.JButton btn_updaterole;
    private Ultilities.swing.ButtonGradient buttonGradient1;
    private Ultilities.swing.ButtonGradient buttonGradient3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_ListProfile;
    private javax.swing.JCheckBox cbk_update;
    private javax.swing.JComboBox<String> cboObjectName;
    private javax.swing.JComboBox<String> cbo_objectname;
    private javax.swing.JCheckBox ckbDelete;
    private javax.swing.JCheckBox ckbInsert;
    private javax.swing.JCheckBox ckbUpdate;
    private javax.swing.JCheckBox ckb_all;
    private javax.swing.JCheckBox ckb_delete;
    private javax.swing.JCheckBox ckb_insert;
    private javax.swing.JCheckBox ckb_select;
    private Ultilities.swing.ComboBoxSuggestion comboBoxSuggestion;
    private javax.swing.JLabel countRecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lb_slProfile;
    private javax.swing.JLabel lb_slProfile1;
    private javax.swing.JLabel lbl_Pass;
    private javax.swing.JLabel numRecord_tab2;
    private javax.swing.JRadioButton rdo_NotPass;
    private javax.swing.JRadioButton rdo_Pass;
    private Ultilities.swing.Table table1;
    private Ultilities.swing.Table table2;
    private Ultilities.swing.Table table_Profile;
    private Ultilities.swing.Table table_tab2;
    private javax.swing.JTextField txtPolicyName;
    private javax.swing.JTextField txt_Pass;
    private javax.swing.JTextField txt_role_name;
    // End of variables declaration//GEN-END:variables
}
