/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.KhachHangGUI;

import BLL.CallExecute;
import BLL.GetData;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phatl
 */
public class KhachHang extends javax.swing.JPanel {

    /**
     * Creates new form KhachHang
     */
    public KhachHang() {
        initComponents();
        loadDataKH();
    }

    GetData x = new GetData();
    private void loadDataKH(){
        ArrayList arr = x.getDataKhachHang();
        DefaultTableModel model = (DefaultTableModel)tb_KH.getModel();
        model.setDataVector((Object[][])arr.get(1), (Object[])arr.get(0));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_KH = new Ultilities.swing.Controls.Table();
        btnXoaKH = new Ultilities.swing.Controls.ButtonGradient();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1100, 700));
        setPreferredSize(new java.awt.Dimension(1100, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_KH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_KH);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 529));

        btnXoaKH.setForeground(new java.awt.Color(0, 0, 0));
        btnXoaKH.setText("Xóa");
        btnXoaKH.setColor1(new java.awt.Color(255, 102, 102));
        btnXoaKH.setColor2(new java.awt.Color(255, 153, 153));
        btnXoaKH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoaKH.setSizeSpeed(5.0F);
        btnXoaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaKHActionPerformed(evt);
            }
        });
        add(btnXoaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 540, 250, 54));
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaKHActionPerformed
        int row = tb_KH.getSelectedRow();
        CallExecute.callDeleteKH_PKH(tb_KH.getValueAt(row, 0).toString());
        //CallExecute.callDeleteKH(tb_KH.getValueAt(row, 0).toString());
        loadDataKH();
    }//GEN-LAST:event_btnXoaKHActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Ultilities.swing.Controls.ButtonGradient btnXoaKH;
    private javax.swing.JScrollPane jScrollPane1;
    private Ultilities.swing.Controls.Table tb_KH;
    // End of variables declaration//GEN-END:variables
}
