/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Role_Priv_Config;

import BLL.ExecuteData;
import BLL.GetData;
import Ultilities.ConvertData.ConvertDataORCL;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HieuThao
 */
public class GrantRole extends javax.swing.JPanel {

    /**
     * Creates new form GrantRole
     */
    private GetData x = new GetData();
    private String user = x.getCurrentUser();
    public GrantRole() {
        initComponents();
        showDataOnTable(tbl_userofrole,x.getRoleofUserToUser(user));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane8 = new javax.swing.JScrollPane();
        tbl_userofrole = new Ultilities.swing.Controls.Table();
        jLabel1 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        btn_grant = new javax.swing.JButton();
        ck_adminoption = new javax.swing.JCheckBox();
        btn_revoke = new javax.swing.JButton();

        tbl_userofrole.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(tbl_userofrole);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tên use");

        txtUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btn_grant.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_grant.setText("Cấp quyền");
        btn_grant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_grantActionPerformed(evt);
            }
        });

        ck_adminoption.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ck_adminoption.setText("with admin option");

        btn_revoke.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_revoke.setText("Thu hồi");
        btn_revoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_revokeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(714, 714, 714)
                .addComponent(btn_grant, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btn_revoke, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ck_adminoption, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ck_adminoption)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_grant, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_revoke, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_grantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_grantActionPerformed
        // TODO add your handling code here:
        int row = tbl_userofrole.getSelectedRow();
        if(row <0)
        {
            JOptionPane.showMessageDialog(this,"Bạn chưa chọn dòng!");
            return;
        }
        if(ck_adminoption.isSelected())
        {
            if(ExecuteData.GrantRoleOfUserAdminOption(txtUser.getText(), tbl_userofrole.getValueAt(row, 1).toString())){
                JOptionPane.showMessageDialog(this,"Cấp quyền cho"+ user +" thành công !");
                showDataOnTable(tbl_userofrole,x.getRoleofUserToUser(user));

            }
            else
            JOptionPane.showMessageDialog(this,"Cấp quyền cho "+ user +" thất bại !");
        }
        else
        {
            if(ExecuteData.GrantRoleOfUser(txtUser.getText(), tbl_userofrole.getValueAt(row, 1).toString())){
                JOptionPane.showMessageDialog(this,"Cấp quyền cho"+ user +" thành công !");
                showDataOnTable(tbl_userofrole,x.getRoleofUserToUser(user));

            }
            else
            JOptionPane.showMessageDialog(this,"Cấp quyền cho "+ user +" thất bại !");
        }
    }//GEN-LAST:event_btn_grantActionPerformed

    private void btn_revokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_revokeActionPerformed
        // TODO add your handling code here:
        int row = tbl_userofrole.getSelectedRow();
        if(row <0)
        {
            JOptionPane.showMessageDialog(this,"Bạn chưa chọn dòng!");
            return;
        }
        if(ExecuteData.RevokeRole( tbl_userofrole.getValueAt(row, 1).toString(),txtUser.getText()))
        {
            JOptionPane.showMessageDialog(this,"Thu hồi role "+ tbl_userofrole.getValueAt(row, 1).toString() + " của "+ user +" thành công !");
            showDataOnTable(tbl_userofrole,x.getRoleofUserToUser(user));

        }
        else
            JOptionPane.showMessageDialog(this,"Thu hồi role của "+ user +" thất bại !");
    }//GEN-LAST:event_btn_revokeActionPerformed
    public void showDataOnTable(Ultilities.swing.Controls.Table table,ArrayList arr)
    {
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        String[] columnNames = (String[])arr.get(0);
        String[][] data = ConvertDataORCL.ConvertObject2DToString2D((Object[][])arr.get(1));
        model.setDataVector(data, columnNames);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_grant;
    private javax.swing.JButton btn_revoke;
    private javax.swing.JCheckBox ck_adminoption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane8;
    private Ultilities.swing.Controls.Table tbl_userofrole;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
